name: CI

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**/*.md'
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable corepack and set Yarn to v4
        run: |
          corepack enable
          corepack prepare yarn@4.5.0 --activate

      - name: Verify yarn installation
        run: yarn --version

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build contracts
        run: yarn build

      - name: Run tests
        run: yarn test
